# Generated by Django 5.1.3 on 2024-11-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image_name",
            field=models.ImageField(upload_to="posts"),
        ),
    ]
